/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstrucoesRouteImport } from './routes/instrucoes'
import { Route as IndexRouteImport } from './routes/index'

const InstrucoesRoute = InstrucoesRouteImport.update({
  id: '/instrucoes',
  path: '/instrucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instrucoes': typeof InstrucoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instrucoes': typeof InstrucoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instrucoes': typeof InstrucoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instrucoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instrucoes'
  id: '__root__' | '/' | '/instrucoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstrucoesRoute: typeof InstrucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instrucoes': {
      id: '/instrucoes'
      path: '/instrucoes'
      fullPath: '/instrucoes'
      preLoaderRoute: typeof InstrucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstrucoesRoute: InstrucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
